version: '3.8'

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  livekit:
    image: livekit/livekit-server:latest
    restart: unless-stopped
    ports:
      - "7880:7880"     # WebSocket/HTTP
      - "7881:7881/udp" # RTC
      - "50000-50100:50000-50100/udp" # RTC port range
    volumes:
      - ./config/livekit.yaml:/etc/livekit.yaml
    command: --config /etc/livekit.yaml
    depends_on:
      - redis
    environment:
      - LIVEKIT_REDIS_HOST=redis:6379

  nests-api:
    build: ./api
    restart: unless-stopped
    ports:
      - "5544:5544"
    env_file:
      - ./api/.env
    environment:
      - LIVEKIT_URL=ws://livekit:7880
      - REDIS_URL=redis://redis:6379
    depends_on:
      - livekit
      - redis
    volumes:
      - ./api/logs:/app/logs

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/ssl:/etc/nginx/ssl
    depends_on:
      - nests-api
      - livekit
    profiles:
      - production

volumes:
  redis_data: